# This workflow deploys the app on push or pull request

name: deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy the app
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - name: Install rsconnect
        run: |
          Rscript -e install.packages("rsconnect"), type = "binary")
      - name: Push to shiny.io
        run: |
          Rscript -e "rsconnect::setAccountInfo(name='apmuhamilton', token=${{secrets.SHINYAPPS_TOKEN}}, secret=${{secrets.SHINYAPPS_SECRET}})"
          Rscript -e "rsconnect::deployApp(appDir = ".", appFiles = list.files(".")[list.files(".") != "data-raw"], appName = "hamiltonCovid19Dashboard", forceUpdate = TRUE, account = "apmuhamilton")"
